name: Petclinic - Deploy App

on:
  push:
    branches:
      - main
env:
  AZURE_WEBAPP_NAME: appsvc-petclinic-java-usc-dev  # set this to your application's name
  PETCLINIC_ROOT_PATH: ${{ github.workspace }}/projects/java-petclinic  # set this to the path to your web app project, relative to the root of the repository
  JAVA_VERSION: '21'                # set this to the Java version to use
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}     # set GH repo secret with the publish profile of the web app
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION}}
          distribution: 'adopt'

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build with Maven
        run: mvn clean package
        working-directory: ${{ env.PETCLINIC_ROOT_PATH }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.PETCLINIC_ROOT_PATH }}/target/*.jar'
          