name: Petclinic - Deploy App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'projects/java-petclinic/**'
env:
  AZURE_WEBAPP_NAME: appsvc-petclinic-java-usc-dev  # set this to your application's name
  PETCLINIC_ROOT_PATH: ${{ github.workspace }}/projects/java-petclinic  # set this to the path to your web app project, relative to the root of the repository
  JAVA_VERSION: '21'                # set this to the Java version to use
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION}}
          distribution: 'adopt'

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build with Maven
        run: mvn clean package
        working-directory: ${{ env.PETCLINIC_ROOT_PATH }}

      - name: Deploy Azure Java JAR with CLI
        run: az webapp deploy --resource-group rg-petclinic-usc-dev --name ${{ env.AZURE_WEBAPP_NAME }} --src-path '${{ env.PETCLINIC_ROOT_PATH }}/target/spring-petclinic.jar'
        env:
          AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}
          PETCLINIC_ROOT_PATH: ${{ env.PETCLINIC_ROOT_PATH }}

          